# Generated by Django 3.2 on 2023-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
